module Xignite
  class Financials < Service

    operations [
      ['GetCompanyFinancialList',                    {}],
      ['GetCompanyFinancial',                        {}],
      ['GetCompaniesFinancial',                      {}],
      ['GetCompaniesFinancialList',                  {}]
    ]

  end
end


# Possible Financials:
#    AccountsPayable
#    AccountsReceivable
#    AccruedExpenses
#    AccruedInterest
#    AccruedInterestPayables
#    AccruedInvestmentIncome
#    AccruedLiabilities
#    AccruedTaxes
#    AccumulatedDepreciationAndDepletion
#    Acquisitions
#    AdditionalPaidInCapital
#    AdjustmentsToRevenue
#    AdvertisingExpenses
#    AllowanceForLoansAndLeaseLosses
#    Amortization
#    AmortizationExpenses
#    AmortizationOfDeferredPolicyAcquisitionCosts
#    AmortizationOfIntangibles
#    AmortizationOfIntangiblesExpenses
#    AssetTurnover
#    AuditorsName
#    AuditorsReport
#    BankersAcceptanceOutstanding
#    BasicEarningsIndicator
#    BasicEPSFromContinuingOperations
#    BasicEPSFromCummulatedEffectOfAccountingChanges
#    BasicEPSFromDiscontinuedOperations
#    BasicEPSFromExtraordinaryIncome
#    BasicEPSFromOtherGainsAndLosses
#    BasicEPSFromTaxLossCarryForwards
#    BasicEPSFromTotalOperations
#    BasicEPSTotal
#    BasicNormalizedNetIncomeShare
#    BasicWeightedSharesOutstanding
#    BookValuePerShare
#    BuildingAndImprovements
#    CapitalLeaseObligations
#    CashAndDueFromBanks
#    CashAndEquivalents
#    CashAsPercentageOfRevenue
#    CashAtBeginningOfPeriod
#    CashAtEndOfPeriod
#    CashDividendsPaid
#    CashFlow
#    CashFlowPerShare
#    CashFromDiscontinuedFinancingActivities
#    CashFromDiscontinuedInvestingActivities
#    CashPerShare
#    ChangeInAssetsReceivables
#    ChangeInIncomeTaxes
#    ChangeInLiabilitiesPayables
#    ChangeOfShortTermDebt
#    ClaimsAndClaimExpense
#    ClosePERatio
#    CommonPar
#    CommonStockEquity
#    ConstructionInProgress
#    CostInExcess
#    CostOfSales
#    CostOfSalesWithDepreciation
#    CumulativeTranslationAdjustment
#    CurrentAndFutureBenefits
#    CurrentAssetsPerShare
#    CurrentDeferredIncomeTaxes
#    CurrentDeferredIncomeTaxLiabilities
#    CurrentLiabilitiesPerShare
#    CurrentRatio
#    DatePreliminaryDataLoaded
#    DeferredAcquisitionCost
#    DeferredIncomeTaxes
#    DeferredIncomeTaxLiabilities
#    DeferredRevenues
#    Depreciation
#    DepreciationAndAmortization
#    DepreciationExpenses
#    DepreciationUnreconciled
#    DilutedEPSFromContinuingOperations
#    DilutedEPSFromCumulatedEffectOfAccountingChanges
#    DilutedEPSFromDiscontinuedOperations
#    DilutedEPSFromExtraordinaryIncome
#    DilutedEPSFromOtherGainsAndLosses
#    DilutedEPSFromTaxLossCarryForward
#    DilutedEPSFromTotalOperations
#    DilutedEPSTotal
#    DilutedEPSYTDFromTotalOperations
#    DilutedNormalizedNetIncomeShare
#    DilutedWeightedSharesOutstanding
#    DividendsPaidPerShare
#    DividendsPaidPerShareYTD
#    DomesticSales
#    DueFromCustomersAcceptance
#    EarningsFromEquityInterest
#    EarningsPeriodIndicator
#    EffectiveTaxRate
#    EffectOfExchangeRateChanges
#    ExciseTaxes
#    ExtraordinaryGainsOrLosses
#    ExtraordinaryIncomeLosses
#    FederalFundsSoldOrSecuritiesPurchased
#    FederalsFundsPurchasedSecuritiesSold
#    FinishedGoods
#    ForeignCurrencyAdjustments
#    ForeignSales
#    FreeCashFlow
#    FreeCashFlowPerShare
#    FuturePolicyBenefits
#    GrossFixedAssets
#    GrossMargin
#    GrossOperatingProfit
#    GrossProfitMargin
#    HighPERatio
#    IncomeAcquiredInProcessRAndD
#    IncomeBeforeIncomeTaxes
#    IncomeFromCumulatedEffectOfAccountingChanges
#    IncomeFromFederalFundsSoldOrPurchased
#    IncomeFromInterestBearingDeposits
#    IncomeFromLoans
#    IncomeFromLoansHeldForResale
#    IncomeFromTaxLossCarryForward
#    IncomeFromTimeDepositsPlaced
#    IncomePerEmployee
#    IncomeRestructuringAndMAndA
#    IncomeTaxes
#    IncomeYTDFromTotalOperations
#    IncreaseOrDecreaseInInventories
#    IncreaseOrDecreaseInOtherCurrentAssets
#    IncreaseOrDecreaseInOtherCurrentLiabilities
#    IncreaseOrDecreaseInOtherWorkingCapital
#    IncreaseOrDecreaseInPayables
#    IncreaseOrDecreaseInPrepaidExpenses
#    IncreaseOrDecreaseInReceivables
#    Intangibles
#    IntangiblesAsPercentageBookValue
#    InterestAsPercentageOfInvestedCapital
#    InterestBearingDeposits
#    InterestBearingDepositsAtOtherBanks
#    InterestCoverageFromContinuingOperations
#    InterestExpense
#    InterestIncome
#    InterestOnCapitalizedLeaseObligations
#    InterestOnDeposits
#    InterestOnFederalFundsPurchasedSold
#    InterestOnLongTermDebt
#    InterestOnShortTermDebt
#    InterimEndingDate
#    Inventories
#    InventoriesAdjustmentsAndAllowances
#    InventoryAsPercentageRevenue
#    InventoryTurnover
#    InventoryValuationMethod
#    InvestedCapital
#    InvestmentBankingProfit
#    InvestmentSecuritiesGain
#    InvestmentSecuritiesIncome
#    IssuanceOfCapitalStock
#    IssuanceOfCommonStock
#    IssuanceOfDebt
#    IssuanceOfLongTermDebt
#    IssuanceOfPreferredStock
#    LandAndImprovements
#    LeaseFinancingIncome
#    LeverageRatio
#    Loans
#    LoansReceivable
#    LongTermDebt
#    LongTermDebtAsPercentageOfInvestedCapital
#    LongTermDebtAsPercentageOfTotalLiabilities
#    LongTermDebtPerShare
#    LongTermDebtToEquityRatio
#    LongTermDebtToTotalCapital
#    LowPERatio
#    MachineryFurnitureAndEquipment
#    MarketableSecurities
#    MGStockNumberIndustryID
#    MinorityInterest
#    MinorityInterestExpense
#    MinorityInterestLiabilities
#    NetCashFromContinuingOperations
#    NetCashFromDiscontinuedOperations
#    NetCashFromFinancingActivities
#    NetCashFromInvestingActivities
#    NetCashFromOperatingActivities
#    NetChangeInCashAndCashEquivalents
#    NetChangeinCashAndEquivalents
#    NetChangeInDeposits
#    NetFixedAssets
#    NetIncomeAvailableForCommon
#    NetIncomeFromContinuingOperations
#    NetIncomeFromDiscontinuedOperations
#    NetIncomeFromTotalOperations
#    NetIncomeOrEarnings
#    NetIncomeOrLoss
#    NetIncreaseFederalFundsSold
#    NetInterestIncomeOrExpense
#    NetInvestmentSecurities
#    NetLoans
#    NetOccupancyExpense
#    NetOtherFinancingCharges
#    NetOtherIncome
#    NetOtherInvestingChanges
#    NetOtherUnearnedLossesGains
#    NetPolicyAcquisitionCosts
#    NetPremiumsReceivables
#    NetProfitMargin
#    NetRealizedCapitalGains
#    NetUnrealizedLossGainOnForeignCurrencies
#    NetUnrealizedLossGainOnInvestments
#    NonCurrentDeferredIncomeTaxes
#    NonInterestBearingDeposits
#    NormalizedClosePERatio
#    NormalizedHighPERatio
#    NormalizedIncome
#    NormalizedIncomePerEmployee
#    NormalizedLowPERatio
#    NormalizedNetProfitMargin
#    NormalizedReturnOnAssets
#    NormalizedReturnOnInvestedCapital
#    NormalizedReturnOnStockEquity
#    NotesPayable
#    NumberOfDaysCostOfGoodsSoldInInventory
#    NumberOfEmployees
#    NumberOfMonthsSinceLastReportingPeriod
#    NumberOfPartTimeEmployees
#    OperatingGainsOrLosses
#    OperatingIncome
#    OperatingIncomeAfterDepreciation
#    OperatingIncomeBeforeDepreciation
#    OperatingRevenue
#    OtherAssets
#    OtherCurrentAssets
#    OtherCurrentLiabilities
#    OtherEquityAdjustments
#    OtherFinancingActivities
#    OtherFixedAssets
#    OtherGainsAndLosses
#    OtherInterestExpense
#    OtherInterestIncome
#    OtherInventories
#    OtherInvestingChangesNet
#    OtherLiabilities
#    OtherMoneyMarketInvestmentsIncome
#    OtherNonCashItems
#    OtherNonCurrentAssets
#    OtherNonCurrentLiabilities
#    OtherNonInterestExpense
#    OtherNonInterestIncome
#    OtherPayables
#    OtherReceivable
#    OtherReceivables
#    OtherServiceCharges
#    OtherSpecialCharges
#    ParticipatingPolicyholderEquity
#    PaymentOfCashDividends
#    PayoutRatio
#    PercentageAssetTurnoverToIndustry
#    PercentageCurrentRatioToIndustry
#    PercentageDebtEquityToIndustry
#    PercentageEarningsToIndustry
#    PercentageEPSToIndustry
#    PercentageGrossProfitMarginToIndustry
#    PercentageLeverageRatioToIndustry
#    PercentageNetProfitMarginToIndustry
#    PercentagePEToIndustry
#    PercentagePostTaxProfitMarginToIndustry
#    PercentagePreTaxProfitMarginToIndustry
#    PercentagePriceBookToIndustry
#    PercentagePriceCashFlowToIndustry
#    PercentagePriceFreeCashFlowToIndustry
#    PercentagePriceSalesToIndustry
#    PercentagePriceToIndustry
#    PercentageReturnOnEquityToIndustry
#    PercentageSalesToIndustry
#    PolicyAcquisitionCosts
#    PolicyHolderFunds
#    PostTaxProfitMargin
#    PreferredDividends
#    PreferredEquityOutsideStockEquity
#    PreferredSecuritiesOfSubsidiaryTrust
#    PreferredSecuritiesOfSubsidiaryTrustLiabilities
#    PreferredShares
#    PreferredStockEquity
#    PreliminaryFullContextIndicator
#    PremisesAndEquipment
#    PremiumsEarned
#    PremiumTaxOrCredit
#    PrepaidExpenses
#    PreTaxIncome
#    PreTaxProfitMargin
#    PriceCashFlowRatio
#    PriceFreeCashFlowRatio
#    PriceToEquityRatio
#    PriceToRevenueRatio
#    PriceToTangibleBookRatio
#    ProceedsFromSaleAndMaturityOfInvestment
#    ProjectedFiscalYearEndDate
#    PromotionAndAdvertising
#    PropertyLiabilityInsuranceClaims
#    ProvisionForLoanLoss
#    ProvisionForLoanLosses
#    PurchasedComponents
#    PurchaseOfInvestmentSecurities
#    PurchaseOfLongTermInvestments
#    PurchaseOfPropertyAndEquipment
#    PurchaseOfPropertyPlantAndEquipment
#    PurchaseOfShortTermInvestments
#    PurchaseOfTreasuryStock
#    QuarterlyIndicator
#    QuickRatio
#    RAndDExpenseAsPercentageOfRevenue
#    RawMaterials
#    RealizedInvestmentGains
#    Receivables
#    ReceivablesAsPercentageOfRevenue
#    ReceivablesPerDaySales
#    ReceivableTurnover
#    RepaymentOfDebt
#    RepaymentOfLongTermDebt
#    RepurchaseOfCapitalStock
#    ResearchAndDevelopmentExpenses
#    RestrictedCash
#    RetainedEarnings
#    ReturnOnAssets
#    ReturnOnInvestedCapital
#    ReturnOnStockEquity
#    RevenuePerCash
#    RevenuePerCommonEquity
#    RevenuePerInvestedCapital
#    RevenuePerPlant
#    RevenuePerShare
#    RevenuesYTD
#    RevenueToAssets
#    SalariesAndEmployeeBenefits
#    SaleOfLongTermInvestments
#    SaleOfPropertyPlantAndEquipment
#    SaleOfShortTermInvestments
#    SalesPerEmployee
#    SalesPerInventory
#    SalesPerReceivables
#    SecurityTransactions
#    SellingGeneralAndAdministrativeExpenses
#    SeparateAccountBusiness
#    SeparateAccountsBusiness
#    ServiceChargeOnDepositAccounts
#    SGAndAExpenseAsPercentageOfRevenue
#    SharesOutstandingCommonClassOnly
#    ShortTermDebt
#    SpecialIncomeCharges
#    TangibleBookValuePerShare
#    TemplateIndicator
#    TimeDepositsPlaced
#    TotalAssets
#    TotalAssetsPerShare
#    TotalCapitalization
#    TotalCommonSharesOutstanding
#    TotalCurrentAssets
#    TotalCurrentLiabilities
#    TotalDebtToEquityRatio
#    TotalEquity
#    TotalFixedAssets
#    TotalIncomeAvailableForInterestExpense
#    TotalInterestExpense
#    TotalInterestIncome
#    TotalLiabilities
#    TotalLiabilitiesAndStockEquity
#    TotalLiabilitiesAsPercentageOfTotalAssets
#    TotalMoneyMarketInvestmentsIncome
#    TotalNetIncome
#    TotalNonCurrentAssets
#    TotalNonCurrentLiabilities
#    TotalNonInterestExpense
#    TotalNonInterestIncome
#    TotalOrdinaryShares
#    TotalRevenue
#    TotalRiskBasedCapitalRatio
#    TradingAccountSecurities
#    TradingAccountSecuritiesIncome
#    TreasuryShares
#    TreasuryStock
#    TrustFeesByCommissions
#    UnearnedPremiumsAssets
#    UnearnedPremiumsLiabilities
#    WorkingCapital
#    WorkingCapitalAsPercentageOfEquity
#    WorkingCapitalAsPercentageOfPrice
#    WorkingCapitalPerShare
#    WorkInProgress#    